# Generated by Django 4.2.4 on 2023-08-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=122)),
                ('content', models.CharField(max_length=522)),
                ('author', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
