# Generated by Django 4.2.4 on 2023-09-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='null', max_length=120),
            preserve_default=False,
        ),
    ]
